Personal_Contact_Project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('contact.urls'))
]

contact/urls.py
from django.urls import path, include
from django.conf.urls.static import static

from Personal_Contact_Project import settings
from contact import views

urlpatterns = [
    path('Home/', views.contactHome, name='home'),
    path('', views.loginUser, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('register/', views.registerUser, name='register'),
    path('Home/add_contact', views.addContact, name='add_contact'),
    path('Home/view_contact', views.viewContact, name='view_contact'),
    path('Home/remove_contact', views.removeContact, name='remove_contact'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contact/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class ContactModel(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    name = models.CharField(max_length=100)
    contact = models.CharField(max_length=10)
    email = models.EmailField(max_length=100, null=True, blank=True)
    CHOISE = (
        ("Friends","Friends"),
        ("Family","Family"),
        ("Office","Office"),
        ("Faculty","Faculty"),
    )
    category = models.CharField(max_length=100, choices=CHOISE)

    def __str__(self):
        return self.name

class LoggedInUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='logged_in_user')
    # Session keys are 32 characters long
    session_key = models.CharField(max_length=32, null=True, blank=True)

contact/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from contact.models import ContactModel


class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactModel
        fields = '__all__'

class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=50)
    class Meta:
        model = User
        fields = ["username","email","password1","password2"]

contact/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect

from Personal_Contact_Project import settings
from contact.models import ContactModel, LoggedInUser
from contact.forms import ContactForm, UserRegistrationForm
import requests
import json

from django.contrib.auth import authenticate, login, logout


@login_required(login_url='login')
def contactHome(request):
    # url = requests.get('http://127.0.0.1:8000/api.contacts/')
    # data = json.loads(url.text)
    data = ContactModel.objects.filter(owner=request.user).order_by('name')
    return render(request, 'index.html', {'contacts': data})
    # try:
    #     user = LoggedInUser.objects.get(user_id=request.user.id)
    #     if user.session_key:
    #         data = ContactModel.objects.filter(owner=request.user).order_by('name')
    #         return render(request,'index.html',{'contacts':data})
    # except:
    #     return HttpResponse("you are not allowed to access this page..!!")


@login_required(login_url='login')
def addContact(request):
    form = ContactForm()
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Contact Saved Successfully')
        else:
            messages.error(request, form.errors)
        return redirect('add_contact')
    return render(request,'add_contact.html',{'form':form})


@login_required(login_url='login')
def viewContact(request):
    contact = ContactModel.objects.get(id=request.GET.get('contact'))
    return render(request,'view_contact.html',{'contact':contact})


def loginUser(request):
    if request.user.is_authenticated:
        return redirect('home')
    elif request.method == 'POST':
        uname = request.POST.get('username')
        pwd = request.POST.get('password')
        rememberme = request.POST.get('rememberme')
        if rememberme is not None:
            settings.SESSION_EXPIRE_AT_BROWSER_CLOSE = False
        user = authenticate(username=uname, password=pwd)
        if user is not None:
            login(request, user=user)
            return redirect('home')

        # if uname == 'admin' and pwd == 'admin':
        #     return redirect('home')

        else:
            messages.error(request, 'Invalid username or password')
            return redirect('login')
    return render(request,'login.html')


def registerUser(request):
    form = UserRegistrationForm(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            obj = form.save(commit=False)
            obj.user = request.user
            obj.save()
            messages.success(request, "Account Successfully Created")
            return redirect('login')
        else:
            messages.error(request, form.errors)
    return render(request, 'register.html',{"form":form})


def logoutUser(request):
    logout(request)
    return redirect('login')

@login_required(login_url='login')
def removeContact(request):
    ContactModel.objects.get(id=request.GET.get('contact')).delete()
    return redirect('home')

templates/add_contact.html
{% extends 'base.html' %}
{% block title %}Contact Book{% endblock %}
{% block body %}
    <style>
    .fa{
        font-size: 42px;
    }
    .add-contact{
        padding: 20px 25%;
    }
    @media screen and (max-width: 770px){
        .heading{
            font-size: 24px;
        }
        .add-contact{
            padding: 10% 5%;
        }
    }
    </style>

    <div class="container">
    <div class="row m-4">
        <div class="col">
            <div class="card bg-info">
                <h1 class="display-4 heading text-center text-light">Add Contact</h1>
                <form action="{% url 'add_contact' %}" method="post">
                    {% csrf_token %}
                    <div class="card text-info add-contact">
                    <input hidden name="owner" id="id_owner" value="{{ request.user.id }}">
                    <a class="text-info" href="{% url 'home' %}" style="text-align: right"><i class="fa fa-chevron-circle-left p-2" aria-hidden="true"></i></a>
                        <label for="id_name">Name:</label><input class="form-control" type="text" name="name" maxlength="100" required="" id="id_name">
                        <label for="id_contact">Contact:</label><input class="form-control" type="text" name="contact" maxlength="10" required="" id="id_contact">
                        <label for="id_email">Email:</label><input class="form-control" type="email" name="email" maxlength="100" id="id_email">
                        <label for="id_category">Category:</label><select class="form-control" name="category" required="" id="id_category">
                          <option value="" selected="">---------</option>

                          <option value="Friends">Friends</option>

                          <option value="Family">Family</option>

                          <option value="Office">Office</option>

                          <option value="Faculty">Faculty</option>

                        </select>
                        {% for x in messages %}
                        <div class="alert-success text-center mt-2 p-2">
                            {{ x }}
                        </div>
                        {% endfor %}

                        <button type="submit" class="btn btn-info mt-4">Submit</button>
                    </div>
                </form>



            </div>
        </div>
    </div>
    </div>
{% endblock %}

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
  <style>
      @media screen and (max-width: 770px){
        .heading{
            font-size: 24px;
        }
        .add-contact{
            padding: 10% 5%;
        }
        .display-4{
            font-size: 32px;
        }
        .fa-plus-circle, .fa-user-circle-o{
            font-size: 32px;
        }
        .fa-chevron-right, .fa-remove{
            font-size: 18px;
        }
      }

  </style>
  </head>
  <body>
  <nav class="navbar navbar-light bg-info text-light">
      <a href="{% url 'home' %}">
        <span class="navbar-brand display-4 text-light"><img src="{% static 'icons8_contact_100px_1.png' %}" width="60">Personal Contact Book</span>
      </a>
      {% if user.is_authenticated %}
      <div class="float-right mx-4">
          <span class="mx-4">Welcome {{ request.user|capfirst }}</span>
          <a href="{% url 'logout' %}" class="btn btn-warning">Logout</a>
      </div>
      {% endif %}
  </nav>
    {% block body %}

    {% endblock %}
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block title %}Contact Book{% endblock %}
{% block body %}
    <style>
    .fa-plus-circle, .fa-user-circle-o{
        font-size: 52px;
    }
    .fa-chevron-right, .fa-remove{
        font-size: 24px;
    }
    @media screen and (max-width: 770px){
        .fa-plus-circle, .fa-user-circle-o{
            font-size: 32px;
        }
        .fa-chevron-right, .fa-remove{
            font-size: 18px;
        }
      }

    </style>
    <div class="container">
    <div class="row m-4">
        <div class="col">
            <div class="card bg-info">
                <h1 class="display-4 text-center text-light p-2">Contact Book</h1>

                <div class="card text-info">
                    <a class="text-info" href="{% url 'add_contact' %}" style="text-align: right"><i class="fa fa-plus-circle p-2" aria-hidden="true"></i></a>
                    {% if contacts %}
                    {% for contact in contacts %}
                    <div class="row pt-2 mx-2">
                        <div class="col-md-2">
                            <i class="fa fa-user-circle-o p-2" aria-hidden="true"></i>
{#                            <i class="fa fa-phone-square p-2" aria-hidden="true"></i>#}
                        </div>
                        <div class="col-md-8">
                                <h5 class="card-title">{{ contact.name }}</h5>
                                <p class="card-text">+91 {{ contact.contact }}</p>
                        </div>
                        <div class="col-md-2">
                            <a class="text-info" href="{% url 'view_contact' %}?contact={{ contact.id }}"><i class="fa fa-chevron-right p-1 mx-4" aria-hidden="true"></i></a>
                            <a class="text-danger" href="{% url 'remove_contact' %}?contact={{ contact.id }}"><i class="fa fa-remove p-1" aria-hidden="true"></i></a>
                        </div>
                    </div>
                    <hr style="width: 90%;margin: 10px auto">
                    {% endfor %}
                    {% else %}
                        <h4 class="text-center p-4">Your Contact List is Empty</h4>
                    {% endif %}
                </div>



            </div>
        </div>
    </div>
    </div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% block title %}Contact Book{% endblock %}
{% block body %}
    <style>
    .fa{
        font-size: 42px;
    }
    .login{
        padding: 10px 30%;
    }
    @media screen and (max-width: 770px){
        .heading{
            font-size: 24px;
        }
        .login{
            padding: 10% 5%;
        }
    }
    </style>
    <div class="container">
    <div class="row m-2" style="margin-top: 10%!important;">
        <div class="col">
            <div class="shadow">
                <h1 class="display-4 heading text-center text-info">Login</h1>
            <hr>
                <form action="{% url 'login' %}" method="post">
                    {% csrf_token %}
                    <div class="text-info login">
                        <label for="id_name">Username</label><input class="form-control form-group-lg" type="text" name="username" maxlength="100" required="">
                        <label for="id_contact" class="mt-2">Password</label><input class="form-control form-group-lg" type="password" name="password" maxlength="10" required="">
                        <div class="p-2">
                            {% for x in messages %}
                                <p class="text-danger text-center"><strong>{{ x }}</strong></p>
                            {% endfor %}
                        </div>
                        <label>
                            <input type="checkbox" name="rememberme" class="checkbox"> remember me
                        </label><br>
                        <button type="submit" class="btn btn-info btn-block">Sign in</button>
                        <p class="float-right">New user? <a href="{% url 'register' %}">sign up</a></p>
                    </div>
                </form>
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320">
                    <path fill="#E7008A" fill-opacity="1" d="M0,64L30,101.3C60,139,120,213,180,250.7C240,288,300,288,360,245.3C420,203,480,117,540,112C600,107,660,181,720,192C780,203,840,149,900,154.7C960,160,1020,224,1080,240C1140,256,1200,224,1260,176C1320,128,1380,64,1410,32L1440,0L1440,320L1410,320C1380,320,1320,320,1260,320C1200,320,1140,320,1080,320C1020,320,960,320,900,320C840,320,780,320,720,320C660,320,600,320,540,320C480,320,420,320,360,320C300,320,240,320,180,320C120,320,60,320,30,320L0,320Z"></path>
                </svg>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% block title %}Contact Book{% endblock %}
{% block body %}
    <style>
    .fa{
        font-size: 42px;
    }
    .login{
        padding: 10px 30%;
    }
    @media screen and (max-width: 770px){
        .heading{
            font-size: 24px;
        }
        .login{
            padding: 10% 5%;
        }
    }
    </style>
    <div class="container">
    <div class="row m-2" style="margin-top: 5%!important;">
        <div class="col">
            <div class="shadow">
                <h1 class="display-4 heading text-center text-info">Registration Form</h1>
            <hr>
                <form action="{% url 'register' %}" method="post">
                    {% csrf_token %}
                    <div class="text-info login">
                        <label for="id_username">User Name</label><input class="form-control" type="text" name="username" maxlength="150" autocapitalize="none" autocomplete="username" autofocus="" required="" id="id_username">
                        <label for="id_email">Email</label><input class="form-control" type="email" name="email" autocomplete="email" required="" id="id_email">
                        <label for="id_password1">Password</label><input class="form-control" type="password" name="password1" autocomplete="new-password" required="" id="id_password1">
                        <label for="id_password2">Password Confirmation</label><input class="form-control" type="password" name="password2" autocomplete="new-password" required="" id="id_password2">
                        <div class="p-2">
                            {% for x in messages %}
                                <p class="text-danger text-center"><strong>{{ x }}</strong></p>
                            {% endfor %}
                        </div>
                        <button type="submit" class="btn btn-info">Sign Up</button>
                    </div>
                </form>
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320">
                    <path fill="#E7008A" fill-opacity="1" d="M0,64L30,101.3C60,139,120,213,180,250.7C240,288,300,288,360,245.3C420,203,480,117,540,112C600,107,660,181,720,192C780,203,840,149,900,154.7C960,160,1020,224,1080,240C1140,256,1200,224,1260,176C1320,128,1380,64,1410,32L1440,0L1440,320L1410,320C1380,320,1320,320,1260,320C1200,320,1140,320,1080,320C1020,320,960,320,900,320C840,320,780,320,720,320C660,320,600,320,540,320C480,320,420,320,360,320C300,320,240,320,180,320C120,320,60,320,30,320L0,320Z"></path>
                </svg>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

templates/view_contact.html
{% extends 'base.html' %}
{% block title %}Contact Book{% endblock %}
{% block body %}
    <style>
    .fa{
        font-size: 34px;
    }
    .view-contact{
        margin: 50px auto;
        font-size: 24px;
        width: 600px
    }
    @media screen and (max-width: 770px){
        .fa{
            font-size: 28px;
        }
        .heading{
            font-size: 24px;
        }
        .view-contact {
            margin: 0;
            font-size: 20px;
            width: 100%;
        }
    }
    </style>

    <div class="container">
    {% for x in messages %}
    <div class="alert-success text-center m-4 p-2">
        {{ x }}
    </div>
    {% endfor %}
    <div class="row m-4">
        <div class="col">
            <div class="card bg-info">
                <h1 class="display-4 heading text-center text-light p-2">Contact Details</h1>
                <form action="{% url 'add_contact' %}" method="post">
                    {% csrf_token %}
                    <div class="card text-info">
                    <a class="text-info" href="{% url 'home' %}" style="text-align: right"><i class="fa fa-chevron-circle-left p-2" aria-hidden="true"></i></a>
                        <div class="content card p-2 text-info view-contact" style="">
                            <p><i class="fa fa-user p-2" aria-hidden="true"></i> {{ contact.name }} </p>
                            <hr>
                            <p><i class="fa fa-phone-square p-2" aria-hidden="true"></i> +91 {{ contact.contact }} </p>
                            <hr>
                            <p><i class="fa fa-envelope p-2" aria-hidden="true"></i> {{ contact.email }} </p>
                            <hr>
                            <p><i class="fa fa-users p-2" aria-hidden="true"></i> {{ contact.category }} </p>
                        </div>
{#                        <table class="table">#}
{#                            <tr>#}
{#                                <th>Name</th>#}
{#                                <th>{{ contact.name }}</th>#}
{#                            </tr>#}
{#                            <tr>#}
{#                                <th>Contact</th>#}
{#                                <th>{{ contact.contact }}</th>#}
{#                            </tr>#}
{#                            <tr>#}
{#                                <th>Email</th>#}
{#                                <th>{{ contact.email }}</th>#}
{#                            </tr>#}
{#                            <tr>#}
{#                                <th>Category</th>#}
{#                                <th>{{ contact.category }}</th>#}
{#                            </tr>#}
{#                        </table>#}
                    </div>
                </form>



            </div>
        </div>
    </div>
    </div>
{% endblock %}